---
title: "Introduction to CppAD"
author: "Kassel Hingee"
date: "15 Feb 2023"
output:  pdf_document
vignette: >
  %\VignetteIndexEntry{Introduction to CppAD}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
bibliography: '`r system.file("REFERENCES.bib", package="scorecompdir")`'
---

This package uses version 2022000.2 of the algorithmic differentiation library `CppAD` [@bradley2023cp] to build score matching estimators. A by-product of this development is a variety of functions for interfacing with `CppAD` objects.

Here is a very very quick taster of `CppAD`, proper help for `CppAD` can be found at <https://cppad.readthedocs.io/>.

Differentiation proceeds by *taping* the basic (*atomic*) operations performed on the independent variables and dynamic parameters. The atomic operations include multiplication, division, addition, sine, cosine, exponential and many more.
Example values for the variables and parameters are used to conduct this taping, so care must be taken with any conditional (e.g. if-then) steps, and `CppAD` has [special tools for this](https://cppad.readthedocs.io/en/latest/CondExp.html).

Once the taping is complete an [`ADFun`](https://cppad.readthedocs.io/en/latest/ADFun.html) object is created.
This tape can be evaluated, differentiated, used for further taping (see [base2ad](https://cppad.readthedocs.io/en/latest/base2ad.html)), solving differential equations and more.
The sequence of operations can also be printed.
The differentiation is with respect to the independent variables, although the dynamic parameters can be altered, allowing for swapping independent variables and dynamic parameters.


# References

