# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @param manifoldname The name of the manifold to transform to. Either 'sphere' or 'simplex'
#' @return An RCpp::XPtr object pointing to the C++ manifold object
NULL

#' @description A lightweight test of a manifold object.
#' Its main benefit is to force compilation of templated functions for the manifold,
#' and to print results to standard output.
#' @param pman An XPtr to a manifold object. Created by `pmanifold()`
#' @return An integer. 0 if the testable parts pass.
NULL

#' @description Apply the `toM` function of a manifold object.
#' @param pman An XPtr to a manifold object. Created by `pmanifold()`.
#' @param u A vector to be transformed to the manifold via `toM`.
#' @return A vector on the manifold.
NULL

#' @param xbetain a concatenated vector of sqrt(x) and beta
#' @param n The dimension of x.
#' @param manifoldname The name of the manifold to transform to
#' @param weightname The name of the weight function to use
#' @param acut The constraint a_c in the weight function
#' @return An RCpp::XPtr object pointing to the ADFun
NULL

#' @param p dimension of measurements
#' @param bd dimension of the parameter vector
#' @param llname name of the likelihood function
#' @return An RCpp::XPtr object pointing to the ADFun
NULL

#' @description Convert an ADFun so that the independent values become dynamic parameters
#' and the dynamic parameters become independent values
#' @param newvalue The value (in the sense after the switch has occured) at which to tape the ADFun
#' @param newdynparam The value of the now dynamic parameters at which to tape the ADFun
#' @return A pointer to an ADFun
NULL

#' @param pfun Rcpp::XPtr to an ADFun with dynamic parameters
#' @param u A vector in the simplex.
#' @param beta a vector of the dynamic parameters
#' @return The Jacobian of pfun
NULL

#' @param pfun Rcpp::XPtr to an ADFun with dynamic parameters
#' @param value A vector in the domain of the taped function.
#' @param theta a vector of the dynamic parameters
#' @return The value of pfun
NULL

#' @param pfun Rcpp::XPtr to an ADFun with dynamic parameters
#' @param u A vector in the simplex.
#' @param beta a vector of the dynamic parameters
#' @return The Hessian of pfun
NULL

#' @param pfun Rcpp::XPtr to an ADFun tape a tape with independent values that are the points to be differentiated with
#' @param value A vector in the domain of the taped function.
#' @param centre A vector in the domain of the taped function to approximate the value from.
#' @param theta a vector of the dynamic parameters
#' @param order The order of Taylor expansion to use.
#' @description Wrapper for the `taylorapprox` C++ function.
#' @return The approximate value of pfun
NULL

#' @param pfun Rcpp::XPtr to an ADFun tape a tape with dynamic parameters and independent parameters
#' @param value A vector in the domain of the taped function.
#' @param thetacentre A vector in the space of the dynamic parameters of the recorded function
#' this vector forms the centre of the Taylor approximation
#' @param theta a vector of the dynamic parameters
#' @param order The order of Taylor expansion to use.
#' @description Taylor expansion in the `theta` dimensions, to approximate the gradient wrt the `value` dimensions.
#' @return The approximate value of the gradient, with respect to theta, of pfun
NULL

#' @param pfun Rcpp::XPtr to an ADFun tape a tape with dynamic parameters and independent parameters
#' @param value A vector in the domain of the taped function.
#' @param thetacentre A vector in the space of the dynamic parameters of the recorded function
#' this vector forms the centre of the Taylor approximation
#' @param theta a vector of the dynamic parameters
#' @param order The order of Taylor expansion to use.
#' @description Taylor expansion in the `theta` dimensions, to approximate the gradient wrt the `value` dimensions.
#' @return The approximate value of the gradient, with respect to theta, of pfun
NULL

pmanifold <- function(manifoldname) {
    .Call('_cdabyppi_pmanifold', PACKAGE = 'cdabyppi', manifoldname)
}

testmanifold <- function(pman, u) {
    .Call('_cdabyppi_testmanifold', PACKAGE = 'cdabyppi', pman, u)
}

ptoM <- function(pman, u) {
    .Call('_cdabyppi_ptoM', PACKAGE = 'cdabyppi', pman, u)
}

ptapesmo <- function(u, theta, pll, pman, weightname, acut, verbose) {
    .Call('_cdabyppi_ptapesmo', PACKAGE = 'cdabyppi', u, theta, pll, pman, weightname, acut, verbose)
}

ptapell <- function(z, theta, llname, pman, fixedtheta, verbose) {
    .Call('_cdabyppi_ptapell', PACKAGE = 'cdabyppi', z, theta, llname, pman, fixedtheta, verbose)
}

swapDynamic <- function(pfun, newvalue, newdynparam) {
    .Call('_cdabyppi_swapDynamic', PACKAGE = 'cdabyppi', pfun, newvalue, newdynparam)
}

pJacobian <- function(pfun, value, theta) {
    .Call('_cdabyppi_pJacobian', PACKAGE = 'cdabyppi', pfun, value, theta)
}

pForward0 <- function(pfun, value, theta) {
    .Call('_cdabyppi_pForward0', PACKAGE = 'cdabyppi', pfun, value, theta)
}

pHessian <- function(pfun, value, theta) {
    .Call('_cdabyppi_pHessian', PACKAGE = 'cdabyppi', pfun, value, theta)
}

pTaylorApprox <- function(pfun, value, centre, theta, order) {
    .Call('_cdabyppi_pTaylorApprox', PACKAGE = 'cdabyppi', pfun, value, centre, theta, order)
}

pTapeJacobianSwap <- function(pfun, value, theta) {
    .Call('_cdabyppi_pTapeJacobianSwap', PACKAGE = 'cdabyppi', pfun, value, theta)
}

pTapeHessianSwap <- function(pfun, value, theta) {
    .Call('_cdabyppi_pTapeHessianSwap', PACKAGE = 'cdabyppi', pfun, value, theta)
}

