# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

corels <- function() {
    .Call('_cdabyppi_corels', PACKAGE = 'cdabyppi')
}

rcpp_hello_world <- function() {
    .Call('_cdabyppi_rcpp_hello_world', PACKAGE = 'cdabyppi')
}

smo_n_grad <- function(xin, betain) {
    .Call('_cdabyppi_smo_n_grad', PACKAGE = 'cdabyppi', xin, betain)
}

